//
// Created by mamin on 12/15/2020.
//
#ifndef CONSTEXPR_QUANTITATIVE_INCLUDE_MATH_COS_H_
#define CONSTEXPR_QUANTITATIVE_INCLUDE_MATH_COS_H_

#endif //CONSTEXPR_QUANTITATIVE_INCLUDE_MATH_COS_H_
